version: '3.9'

services:
  backend:
    build: .
    container_name: antiscam-bank-app
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - ./app:/app/app  
      - ./main.py:/app/main.py
