version: '3.9'

services:
  backend:
    build: .
    container_name: antiscam-bank-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - neo4j
    volumes:
      - ./src:/app/src

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5.11
    container_name: neo4j_graph
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data

volumes:
  mongodb_data:
  redis_data:
  neo4j_data:
